services:
  # メインWebアプリケーション
  - type: web
    name: miniloto-prediction-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 600 --workers 1 --max-requests 100 --preload --worker-class sync --worker-connections 1000 --max-requests-jitter 10
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        generateValue: true
      # メモリ最適化
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      # Celery設定（Redis有料枠使用）
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: miniloto-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: miniloto-redis
          property: connectionString
      # ローカルストレージ使用（ダウンロード/アップロード対応）
      - key: USE_LOCAL_STORAGE
        value: "true"
      - key: DATA_DIR
        value: /tmp/miniloto_data
    # disk削除（無料枠では使用不可）
    healthCheckPath: /
    autoDeploy: true
    region: oregon

  # Celeryワーカー（バックグラウンドタスク処理）
  - type: worker
    name: miniloto-celery-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      # メモリ最適化
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      # Celery設定（Redis有料枠使用）
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: miniloto-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: miniloto-redis
          property: connectionString
      # ワーカー設定
      - key: CELERY_WORKER_CONCURRENCY
        value: "1"
      - key: CELERY_WORKER_MAX_MEMORY
        value: "400000"
      # ローカルストレージ使用
      - key: USE_LOCAL_STORAGE
        value: "true"
      - key: DATA_DIR
        value: /tmp/miniloto_data
    # disk削除（無料枠では使用不可）
    autoDeploy: true
    region: oregon

  # Redis（有料枠使用）
  - type: redis
    name: miniloto-redis
    plan: standard
    region: oregon
    maxmemoryPolicy: allkeys-lru